Traceback (most recent call last):
  File "C:\Users\sofmo\miniconda3\envs\dataviz_tarea1\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\sofmo\miniconda3\envs\dataviz_tarea1\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\sofmo\miniconda3\envs\dataviz_tarea1\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\sofmo\miniconda3\envs\dataviz_tarea1\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\sofmo\miniconda3\envs\dataviz_tarea1\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\sofmo\miniconda3\envs\dataviz_tarea1\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\sofmo\miniconda3\envs\dataviz_tarea1\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Sports2016 = pd.crosstab(index = olympics2016['Sport'], columns = 'count')
Sports2016.plot(kind = 'bar');
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mImportError[0m                               Traceback (most recent call last)
Cell [1;32mIn[5], line 2[0m
[0;32m      1[0m Sports2016 [38;5;241m=[39m pd[38;5;241m.[39mcrosstab(index [38;5;241m=[39m olympics2016[[38;5;124m'[39m[38;5;124mSport[39m[38;5;124m'[39m], columns [38;5;241m=[39m [38;5;124m'[39m[38;5;124mcount[39m[38;5;124m'[39m)
[1;32m----> 2[0m [43mSports2016[49m[38;5;241;43m.[39;49m[43mplot[49m[43m([49m[43mkind[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mbar[39;49m[38;5;124;43m'[39;49m[43m)[49m;

File [1;32m~\miniconda3\envs\dataviz_tarea1\lib\site-packages\pandas\plotting\_core.py:947[0m, in [0;36mPlotAccessor.__call__[1;34m(self, *args, **kwargs)[0m
[0;32m    946[0m [38;5;28;01mdef[39;00m [38;5;21m__call__[39m([38;5;28mself[39m, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m--> 947[0m     plot_backend [38;5;241m=[39m [43m_get_plot_backend[49m[43m([49m[43mkwargs[49m[38;5;241;43m.[39;49m[43mpop[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mbackend[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;28;43;01mNone[39;49;00m[43m)[49m[43m)[49m
[0;32m    949[0m     x, y, kind, kwargs [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_get_call_args(
[0;32m    950[0m         plot_backend[38;5;241m.[39m[38;5;18m__name__[39m, [38;5;28mself[39m[38;5;241m.[39m_parent, args, kwargs
[0;32m    951[0m     )
[0;32m    953[0m     kind [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_kind_aliases[38;5;241m.[39mget(kind, kind)

File [1;32m~\miniconda3\envs\dataviz_tarea1\lib\site-packages\pandas\plotting\_core.py:1944[0m, in [0;36m_get_plot_backend[1;34m(backend)[0m
[0;32m   1941[0m [38;5;28;01mif[39;00m backend_str [38;5;129;01min[39;00m _backends:
[0;32m   1942[0m     [38;5;28;01mreturn[39;00m _backends[backend_str]
[1;32m-> 1944[0m module [38;5;241m=[39m [43m_load_backend[49m[43m([49m[43mbackend_str[49m[43m)[49m
[0;32m   1945[0m _backends[backend_str] [38;5;241m=[39m module
[0;32m   1946[0m [38;5;28;01mreturn[39;00m module

File [1;32m~\miniconda3\envs\dataviz_tarea1\lib\site-packages\pandas\plotting\_core.py:1874[0m, in [0;36m_load_backend[1;34m(backend)[0m
[0;32m   1872[0m         module [38;5;241m=[39m importlib[38;5;241m.[39mimport_module([38;5;124m"[39m[38;5;124mpandas.plotting._matplotlib[39m[38;5;124m"[39m)
[0;32m   1873[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:
[1;32m-> 1874[0m         [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(
[0;32m   1875[0m             [38;5;124m"[39m[38;5;124mmatplotlib is required for plotting when the [39m[38;5;124m"[39m
[0;32m   1876[0m             [38;5;124m'[39m[38;5;124mdefault backend [39m[38;5;124m"[39m[38;5;124mmatplotlib[39m[38;5;124m"[39m[38;5;124m is selected.[39m[38;5;124m'[39m
[0;32m   1877[0m         ) [38;5;28;01mfrom[39;00m [38;5;28;01mNone[39;00m
[0;32m   1878[0m     [38;5;28;01mreturn[39;00m module
[0;32m   1880[0m found_backend [38;5;241m=[39m [38;5;28;01mFalse[39;00m

[1;31mImportError[0m: matplotlib is required for plotting when the default backend "matplotlib" is selected.

